version: '3.8'

services:
  transaction_postgres:
    image: postgres
    container_name: transaction_postgres
    read_only: true
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=transactionDb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - transaction-volume:/var/lib/postgresql/data
    command: -p 5432

volumes:
  transaction-volume: